### ISSUE TITLE
Repository and errors

### ISSUE THREAD

**Issue by mickeyn** [mickeyn/PONAPI#29]
We are passing $doc to the repository object and expect it to raise the error (reasonable) but also set the error (which is a spec thing and we lose control of).
I think we should provide (probably in PONAPI::DAO::Repository) a generic way to raise errors where we ensure the status codes (and maybe other info pieces) based on a reported scenario and according to the spec.

**Comment by mickeyn** [comment]
can also be done in the builder, if we provide optional errors to be passed as input - the doc can set the status and anything else in itself.

**Comment by Hugmeir** [comment]
This is partially fixed now that we're using exception objects. Partially because we're still doing things like this:

```
        if ( $err_id && $err_id == SQLITE_CONSTRAINT ) {
            PONAPI::DAO::Exception->throw(
                message   => "Table constraint failed: $errstr",
                sql_error => 1,
                status    => 409,
            );
        }
```

But broadly speaking, the way for repos to report errors now is to throw an exception, not to use `->raise_error`.
Currently repos can set the status manually, but we could just provide more subclasses of PONAPI::DAO::Exception and let them use what fits the situation best (in the above, we could have an overly specific one, ala PONAPI::DAO::Exception::SQL::ConstraintFailed)

**Comment by Hugmeir** [comment]
All handled by exceptions now.
