### ISSUE TITLE
Should repositories set HTTP status codes?

### ISSUE THREAD

**Issue by Hugmeir** [mickeyn/PONAPI#32]
Currently, we let the underlaying repo handle most of the HTTP status codes; This means that they end up calling $doc->set_status($code).

This means the DAO has no way of checking if the repo is conforming to the spec, and whoever writes a repo needs to know the spec to set the appropriate codes.

Might be worth trying adding constants or convenience methods to the document, ala

```
$doc->deferred_processing;
$doc->no_content;
$doc->used_client_provided_id; # alias to ->no_content
```

**Comment by mickeyn** [comment]
related to #29 :)

**Comment by stevan** [comment]
Why can't people just use [HTTP::Status](https://metacpan.org/pod/HTTP::Status)? We can also use it to verify things such as `is_error`, etc.

**Comment by mickeyn** [comment]
they can, since those are just numbers and the set_status will accept them (I think we should use it in the examples in the docs, it's just nicer).

with errors, I don't think we have a problem as 4xx/5xx are accepted by the spec (so if you feel like a 'tea pot'...) - though we can normalize them to 400/500 in case of multiple errors (http://jsonapi.org/format/#errors-processing).

the issue is mostly with the specific success codes for create/delete according to the spec, which requires spec knowledge.

**Comment by Hugmeir** [comment]
Solved by constants + exceptions.
